//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE2.LabManager.Data.Contracts {
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    [DbConfigurationType(typeof(MySql.Data.Entity.MySqlEFConfiguration))]
    public partial class se02team06 : DbContext {
        public se02team06()
            : base("name=se02team06") {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder) {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<lab> labs { get; set; }
        public virtual DbSet<labdate> labdates { get; set; }
        public virtual DbSet<lecturer> lecturers { get; set; }
        public virtual DbSet<present> presents { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<taskdone> taskdones { get; set; }
    }
}
