//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE2.LabManager.Data.Contracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class labdate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public labdate()
        {
            this.presents = new HashSet<present>();
        }
    
        public int labdateID { get; set; }
        public System.DateTime date { get; set; }
        public int lab_labID { get; set; }
    
        public virtual lab lab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<present> presents { get; set; }
    }
}
