//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SE2.LabManager.Data.Contracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskdone
    {
        public int taskDoneID { get; set; }
        public sbyte isDone { get; set; }
        public int student_studentID { get; set; }
        public int task_taskID { get; set; }
    
        public virtual student student { get; set; }
        public virtual task task { get; set; }
    }
}
